### ISSUE TITLE
(feat) Support "lite" syntax for aliases 

### ISSUE THREAD

**Issue by nobiot** [nobiot/md-roam#43]
This is the current syntax to define aliases. Compliant with YAML syntax, and works great. 

  ```
   roam_alias: [ alias 1, 'alias 2', "alias 3" ]
   ```
I feel that I would like to have an option to also support
```
roam_alise: alias 1, alise 2
```
and/or
```
aliases: [alias 1, alias 2]
```
The latter is compatible with [gatsby-themes-brain](https://github.com/aengusmcmillin/gatsby-theme-brain#add-frontmatter-for-titles-and-aliases)

Let's how far this idea can be implemented.

**Comment by romariorobby** [comment]
I'd like to see this support as well especially the second option. Currently I use emacs and logseq. it seems logseq parse `[` and `"` incorrectly and create their own page. suppose to just ignore it. i know its not relevant but it would be nice to incorperate with other app as well.

**Comment by nobiot** [comment]
What would you really like? The second option is this: `aliases: [alias 1, alias 2]`, which contains `[`.  

Have you already tried the syntax you would like to use? And what is the syntax you would like to use?

**Comment by romariorobby** [comment]
No, I mean this  `alias: alias 1, alias 2` which doesn't contain `[` and `"`

**Comment by romariorobby** [comment]
My setup currently something like this: 
```yaml
title: title
id: id
roam_aliases: [ "alias1", "alias2" ] // emacs (md-roam) alias
aliases: alias1    // Obsidian alias
alias:: alias1      // Logseq alias
```
