### ISSUE TITLE
What is the minimal requirement for md files to be recognized as org-roam nodes? Thank you very much.

### ISSUE THREAD

**Issue by suliveevil** [nobiot/md-roam#70]
All my 20000 Obsidian notes have this YAML:

```yaml
---
title: "callout_test"
categories: 
date: 2022-11-11 05:38:40 +0800
tags: 
excerpt: 
---
```

**Comment by suliveevil** [comment]
Do I have to change all front-matter YAML to this style?

Can I leave `category` `roam_refs` `roam_aliases` empty?

Thank you very much.

```yaml
---
title: callout_test
id: 2022-11-11T053840
category: 
roam_refs : 
roam_aliases :
---
```
